### ISSUE TITLE
Script tag generated by `django_htmx_script` shouldn't contain `type="text/javascript"`

### ISSUE THREAD

**Issue by bittner** [adamchainz/django-htmx#346] opened 2023-06-28 17:16 UTC
### Python Version

3.10.11

### Django Version

4.2.2

### Package Version

1.15.0

### Description

The `{% django_htmx_script %}` template tag generates a HTML script tag having `type="text/javascript"` inside of it.

The [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) say about using the `type` attribute:

> Authors are encouraged to omit the attribute if the script refers to JavaScript code

Is there a reason why the attribute is used? (e.g. backward compatibility)

Would you accept a PR that removes the attribute?

**Comment by adamchainz** [comment] 2023-07-03 10:27
Caused by my ignorance. Fixed in #347, with co-authored-by for ya so you get the PR point.

**Closed** 2023-07-03 10:27 UTC

**Comment by bittner** [comment] 2023-07-03 12:22
Thanks Adam! :1st_place_medal:
