### ISSUE TITLE
HX-Reselect response header not implemeted

### ISSUE THREAD

**Issue by p-baum** [adamchainz/django-htmx#378] opened 2023-10-10 11:02 UTC
### Description

From the HTMX docs:

> HX-Reselect
> a CSS selector that allows you to choose which part of the response is used to be swapped in. Overrides an existing hx-select on the triggering element

**Comment by adamchainz** [comment] 2023-10-10 15:11
Dupe of #354

**Closed by adamchainz** 2023-10-10 15:11 UTC
